#!/bin/sh
#Configuration du pare feu au demarrage.
#Met enplace un fire wall et partage de connexion internet.
#A déplacer dans : /etc/init.d/
#chmod +x /etc/init.d/iptables
#update-rc.d iptables start 99 2 . stop 00 2 0 1 6 .

#Interface du reseau local
Interface_Local=eth0;
#Interface du reseau d'acces à internet (livebox)
Interface_Internet=eth1;

initNetfilter() {
	####################################################################################################
	#  Initialise les tables netfilter
	####################################################################################################
	echo "Initialise les tables netfilter"
	
	# Initialise la table Filter (par défaut tout les échanges sont refusés)
	echo "+ Initialisation de la table Filter"
	iptables -t filter -F
	iptables -t filter -X 
	iptables -t filter -P INPUT   DROP
	iptables -t filter -P FORWARD DROP
	iptables -t filter -P OUTPUT  DROP
	
	# Initialise la table NAT (par défaut tout les échanges sont activés)
	echo "+ Initialisation de la table NAT"
	iptables -t nat -F
	iptables -t nat -X 
	iptables -t nat -P PREROUTING  ACCEPT
	iptables -t nat -P OUTPUT      ACCEPT
	iptables -t nat -P POSTROUTING ACCEPT
	
	# Initialise la table Mangle (par défaut tout les échanges sont activés)
	echo "+ Initialisation de la table Mangle"
	iptables -t mangle -F
	iptables -t mangle -X 
	iptables -t mangle -P PREROUTING  ACCEPT
	iptables -t mangle -P INPUT       ACCEPT
	iptables -t mangle -P FORWARD     ACCEPT
	iptables -t mangle -P OUTPUT      ACCEPT
	iptables -t mangle -P POSTROUTING ACCEPT
	
	echo "+ Desactivation du NAT"
	echo 0 > /proc/sys/net/ipv4/ip_forward
	####################################################################################################
}

ipMask() {
	#####################################################################################################
	# Met en place le masquage ip
	#####################################################################################################
	echo "Met en place le masquage ip (l'IP masquerading)"
	
	modprobe iptable_nat
	modprobe ip_nat_ftp
	modprobe ip_nat_irc
	
	iptables -t filter -A FORWARD -i $Interface_Local -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p all -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Internet -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.0/16 -p all -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	iptables -t nat    -A POSTROUTING               -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p all -j MASQUERADE
	
	echo 1 > /proc/sys/net/ipv4/ip_forward
	####################################################################################################
}

start() {
	
	initNetfilter
	
	####################################################################################################
	# Autorise les connexions locales
	####################################################################################################
	echo "Autorise les connexions locales"
	
	# Autorise la boucle locale
	iptables -t filter -A OUTPUT -o lo -p all -j ACCEPT
	iptables -t filter -A INPUT  -i lo -p all -j ACCEPT
	
	iptables -t filter -A OUTPUT -o $Interface_Local -s 172.16.0.1 -d 172.16.0.0/16 -p all -j ACCEPT
	iptables -t filter -A INPUT  -i $Interface_Local -s 172.16.0.0/16 -d 172.16.0.1 -p all -j ACCEPT
	
	iptables -t filter -A OUTPUT -o $Interface_Local -s 172.16.0.1 -d 172.16.255.255 -p all -j ACCEPT
	iptables -t filter -A INPUT  -i $Interface_Local -s 172.16.255.255 -d 172.16.0.1 -p all -j ACCEPT
	#####################################################################################################
	
	
	#####################################################################################################
	# Autorise la communication vers/depuis l'exterieur
	#####################################################################################################
	echo "Autorise la communication vers/depuis l'exterieur (suivi de cennexion) "
	modprobe ip_conntrack
	modprobe ip_conntrack_ftp
	modprobe ip_conntrack_irc
	
	iptables -t filter -A OUTPUT -o $Interface_Internet -s 192.168.1.50 -d 192.168.1.0/24 -p all -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A INPUT  -i $Interface_Internet -s 192.168.1.0/24 -d 192.168.1.50 -p all -m state --state RELATED,ESTABLISHED -j ACCEPT
	#####################################################################################################
	
	
	#####################################################################################################
	# Met en place la redirection de port pour le serveur web
	#####################################################################################################
	# Chargement des modules pour le port forwarding
	modprobe iptable_nat
	
	echo "Met en place la redirection de port pour le serveur web (port forwarding)"
	iptables -t filter -A FORWARD -i $Interface_Internet -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.0/16 -p tcp --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Local -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p tcp --sport 80 -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Internet -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.0/16 -p udp --dport 80 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Local -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p udp --sport 80 -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	iptables -t filter -A FORWARD -i $Interface_Internet -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.0/16 -p tcp --dport 443 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Local -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p tcp --sport 443 -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Internet -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.0/16 -p udp --dport 443 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -t filter -A FORWARD -i $Interface_Local -o $Interface_Internet -s 172.16.0.0/16 -d 192.168.1.0/24 -p udp --sport 443 -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	iptables -t nat    -A PREROUTING                -i $Interface_Internet -s 192.168.1.0/24 -d 192.168.1.50      -p tcp --dport 80 -j DNAT --to-destination 172.16.0.10
	iptables -t nat    -A POSTROUTING               -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.10      -p tcp --dport 80 -j SNAT --to-source 172.16.0.10
	iptables -t nat    -A PREROUTING                -i $Interface_Internet -s 192.168.1.0/24 -d 192.168.1.50      -p udp --dport 80 -j DNAT --to-destination 172.16.0.10
	iptables -t nat    -A POSTROUTING               -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.10      -p udp --dport 80 -j SNAT --to-source 172.16.0.10
	
	iptables -t nat    -A PREROUTING                -i $Interface_Internet -s 192.168.1.0/24 -d 192.168.1.50      -p tcp --dport 443 -j DNAT --to-destination 172.16.0.10
	iptables -t nat    -A POSTROUTING               -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.10      -p tcp --dport 443 -j SNAT --to-source 172.16.0.10
	iptables -t nat    -A PREROUTING                -i $Interface_Internet -s 192.168.1.0/24 -d 192.168.1.50      -p udp --dport 443 -j DNAT --to-destination 172.16.0.10
	iptables -t nat    -A POSTROUTING               -o $Interface_Local -s 192.168.1.0/24 -d 172.16.0.10      -p udp --dport 443 -j SNAT --to-source 172.16.0.10
	#####################################################################################################
	
	ipMask
}

stop() {
	
	echo "Autorise toute les connexions"
	
	# Suppression de toutes les chaînes pré-définies de la table FILTER
	iptables -t filter -F
	
	# Suppression de toutes les chaînes utilisateur de la table FILTER
	iptables -t filter -X
	
	# Par defaut, toute les paquets de la table FILTER sont acceptés
	iptables -t filter -P INPUT ACCEPT
	iptables -t filter -P OUTPUT ACCEPT
	iptables -t filter -P FORWARD ACCEPT
	
	# Suppression de toutes les chaînes pré-définies de la table NAT
	iptables -t nat -F
	
	# Suppression de toutes les chaînes utilisateur de la table NAT
	iptables -t nat -X
	
	# Par defaut, toute les paquets de la table NAT sont acceptés
	iptables -t nat -P PREROUTING ACCEPT
	iptables -t nat -P OUTPUT ACCEPT
	iptables -t nat -P POSTROUTING ACCEPT
	
	
	
	# Suppression de toutes les chaînes pré-définies de la table MANGLE
	iptables -t mangle -F
	
	# Suppression de toutes les chaînes utilisateur de la table MANGLE
	iptables -t mangle -X
	
	# Par defaut, toute les paquets de la table MANGLE sont acceptés
	iptables -t mangle -P PREROUTING ACCEPT
	iptables -t mangle -P INPUT ACCEPT
	iptables -t mangle -P OUTPUT ACCEPT
	iptables -t mangle -P FORWARD ACCEPT
	iptables -t mangle -P POSTROUTING ACCEPT
	
	ipMask
	
	# Desactive les options anti-spoofing du kernel
	for Filter in /proc/sys/net/ipv4/conf/*/rp_filter; do
	  echo 0 > $Filter
	done
	
	# Desactive les options anti-ping du kernel
	echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_all
	echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
	echo 0 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
}

case "$1" in
start)
	start
	;;

stop)
	stop
	;;
restart)
	stop && start
	;;
*)
	echo "Usage $0 {start|stop|restart}"
	exit 1
esac

exit 0
